# Generated by Django 3.1.3 on 2020-11-18 19:24

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201119_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=stdimage.models.JPEGField(upload_to=''),
        ),
    ]
